name: duplicati
services:
  duplicati:
    container_name: duplicati
    image: ghcr.io/oriolrius/duplicati
    env_file:
    - .env
    volumes:
    - /:/mnt
    - /backup:/backup
    - ./data:/data
    - .${DUPLICATI__IMPORT_CONFIG:-/import}:/import
    restart: unless-stopped
    build: .
    network_mode: host
